snex: stdout > stderr

diff --git a/linux/snex b/linux/snex
--- a/linux/snex
+++ b/linux/snex
@@ -1,15 +1,14 @@
 #!/bin/bash
 cmd="$(snippet "$@")"
-echo "$cmd"
-echo ""
-
+echo "$cmd" >&2
+echo "" >&2
 while true; do
-    echo         "--------------"
+    echo         "--------------" >&2
     read -rn1 -p "Execute? [y/N] " answer
-    echo
+    echo >&2
     case "$answer" in
         y|Y) bash -c "$cmd"; break ;;
-        ""|n|N)  echo "Aborted."; break ;;
-        *)   echo "Press 'y' to execute or Enter to abort." ;;
+        ""|n|N)  echo "Aborted." >&2; break ;;
+        *)   echo "Press 'y' to execute or Enter to abort." >&2 ;;
     esac
 done
